---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Education
<p style="text-align:left;">
    Columbia University Irving Medical Center
    <span style="float:right;">
        Expected graduation: May 2021  </p>  
M.S. Biostatistics  

<p style="text-align:left;">
    University of California, Irvine
    <span style="float:right;">
        September 2017 – June 2021</p>  
B.S. Biological Sciences    

Honors: Dean’s List (6 quarters)

## Internship 
__Kexing Biopharm__ 
<p style="text-align:left;">
    _Clinical Intern_
    <span style="float:right;">
        January 2021 – April 2021  
    </span>
</p>
•	Assisted in the research, market investigation and project initiation proposal of a wAMD drug target  
•	Assisted in the writing of project initiation proposal for a Chlamydia Trachomatis drug target  
•	Presented literature findings of exosome as a drug delivery system and market investigation of mRNA vaccine  
•	Participated in the inspection and audit of hospitals  		

## Experience
__UCI Health__  
<p style="text-align:left;">
    _Clinical Research Assistant_
    <span style="float:right;">
        September 2019 - May 2021
    </span>
</p>
•	Assistant for the Center for Artificial Intelligence and Diagnostic Medicine (CAIDM)  
•	Annotated on CT scans of UCI Health patients of pneumonia and stroke project to develop patterns for deep learning of Artificial Intelligence  
•	Created written reports of annotation progress   
•	Participated in team meetings and project updates  
•	Literature review on cerebral calcification using PubMed and Google Scholar  
•	Created radiology report review for COVID-19 project  

__Department of Chemistry, University of California, Irvine__   
<p style="text-align:left;">
    _Learning Assistant_
    <span style="float:right;">
        September 2020 - December 2020 
    </span>
</p>
•	Assisted Teaching Assistant in lab session in a remote teaching format  
•	Participated in weekly team meeting   
•	Answered questions on a learning management system where students can ask questions in a forum-type format  

__actOC COVID-19 Community Surveillance Study__  
<p style="text-align:left;">
    _Volunteer_
    <span style="float:right;">
        July 2020 - August 2020 
    </span>
</p>
•	Checked in volunteers for the actOC seroprevalence testing of COVID-19 antibodies study  
•	Assisted in running the testing sites and assembling supplies  

__United Nations International Children’s Emergency Fund (UNICEF)__   	
<p style="text-align:left;">
    _Member_
    <span style="float:right;">
        September 2018 - March 2020 
    </span>
</p>
•	Participated in the Spooktacular Fun Days Festival in Orange County, assisted in setting up, directed participants into the venue, and provided translation service  
•	Regularly took part in public welfare activities organized by UNICEF, and provided volunteer services in publicity events aimed at protecting and caring for children  

__Anteater Emergency Medical Services (Stop the bleed: save a life)__    
<p style="text-align:left;">
    _Active Participant_
    <span style="float:right;">
        November 2018 - January 2019 
    </span>
</p>
•	Participated in learning the theoretical knowledge of first aid and first aid exercises, awarded certificate of completion of the “Bleeding Control Basic v. 1.0 Course”  
•	Learned to use tourniquet, direct pressure, and wound packing to stop a life-threatening bleeding, became proficient in how to rescue patients with sudden bleeding situation in the fastest manner  

## Language
Mandarin(native), Cantonese(native), English(fluent), Spanish(basic)

## Certifications
Certified Learning Assistant, UC Irvine  
Bleeding Control Basic v. 1.0 Course, Anteater Emergency Medical Services & UCI Trauma Center  
Good Clinical Practice, CITI  
Lab Animal Research, CITI   
Human Subject Research, CITI  


